version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: events-service-postgres
    environment:
      POSTGRES_DB: events_service
      POSTGRES_USER: events_user
      POSTGRES_PASSWORD: events_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U events_user -d events_service"]
      interval: 30s
      timeout: 10s
      retries: 5


  migrate:
    image: migrate/migrate
    command: -path=/mocks -database postgres://events_user:events_password@postgres:5432/events_service?sslmode=disable up
    volumes:
      - ./mocks:/mocks
    depends_on:
      postgres:
        condition: service_healthy

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: events-service-go
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: events_user
      DB_PASSWORD: events_password
      DB_NAME: events_service
      DB_SSLMODE: disable
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: